"""-----ANALYSIS PROPERTIES-----"""
INTERPOLATE = 'ffill'
INTERPOLATE_PARAMETERS = {}
MEAN_KEYWORD = 'mean'

CALC_DATE_KEY = 'calculation_date'
PROCESS_TYPE_KEY = 'process_type'
VERSION_KEY = 'version_number'
MESSAGE_TYPE_KEY = 'message_type'
SENDER_MRID_KEY = 'sender.mRID'
RECEIVER_MRID_KEY = 'receiver.mRID'
SENDER_MARKET_ROLE_KEY = 'sender.market_role_type'
POINT_RESOLUTION_KEY = 'point_resolution'
AVAILABLE_POSITION_KEY = 'available.position'
AVAILABLE_VALUE_KEY = 'available.value'
PERCENTAGE_VALUE_KEY = 'percentage_level.value'
MRID_KEY = 'mrid'
LFC_BLOCK_MRID_KEY = 'LFC_block.mRID'
BUSINESS_TYPE_KEY = 'business_type'
DOMAIN_MRID_KEY = 'domain.mRID'
DOMAIN_NAME_KEY = 'domain.name'
IN_DOMAIN_MRID_KEY = 'in_domain.mRID'
OUT_DOMAIN_MRID_KEY = 'out_domain.mRID'
CURVE_TYPE_KEY = 'curve_type'
DIRECTION_CODE_KEY = 'direction.code'
DIRECTION_NAME_KEY = 'direction.name'
TYPE_NAME_KEY = 'type.name'
TYPE_DESCRIPTION_KEY = 'type.description'
PERCENTAGE_UNIT_KEY = 'percentage_level.measurement_unit'
AVAILABLE_UNIT_KEY = 'available.measurement_unit'
SERIES_VALID_TO_KEY = '_series_valid_to'
SERIES_VALID_FROM_KEY = '_series_valid_from'
SERIES_VALID_TO_F_KEY = 'series_valid_to'
SERIES_VALID_FROM_F_KEY = 'series_valid_from'
VALID_FROM_KEY = 'valid_from'
VALID_TO_KEY = 'valid_to'
PRODUCT_KEY = 'product'
DATA_PERIOD_START_KEY = 'data_period_start'
DATA_PERIOD_END_KEY = 'data_period_end'
RESULT_TYPE_KEY = 'result_type'

QUANTILE_START_KEY = 'quantile_spacing.start_percentage'
QUANTILE_STEP_KEY = 'quantile_spacing.step_percentage'
QUANTILE_STOP_KEY = 'quantile_spacing.stop_percentage'

POINT_QUANTITY_KEY = 'Point.quantity'
POINT_POSITION_KEY = 'Point.position'

MARKET_PRODUCT_TYPE_KEY = 'Standard_MarketProduct.marketProductType'
